### ISSUE TITLE
Skip translated stories

### ISSUE THREAD

**Issue by espensj** [global-asp/global-asp#10]
I would like to see a button/link for skipping translated stories. I have to flip through 10 stories in Norwegian to get to the first that has not already been translated. Something like this:

![screen shot 2016-01-17 at 11 46 51 am](https://cloud.githubusercontent.com/assets/12679303/12379487/b6d18826-bd10-11e5-93a5-178dd13c8a06.png)

**Comment by dohliam** [comment]
Good idea... moved to the [gasp-translator repo](https://github.com/dohliam/gasp-translator/issues/16).
