### ISSUE TITLE
A home page for each story?

### ISSUE THREAD

**Issue by espensj** [global-asp/global-asp#11]
I was looking at a random story, and I thought: has it been translated into other languages? What is the original (English) title? 

The story code is 0253 – wouldn't it be nice to be able to click on that number to get to a "home page" for that story, with the text in English and a list of translations? Perhaps some other tidbits?

![screen shot 2016-03-13 at 1 13 15 pm](https://cloud.githubusercontent.com/assets/12679303/13731054/8b1363b0-e91d-11e5-9520-bd56ff78d8be.png)

**Comment by dohliam** [comment]
All of this information is already available on the Global ASP homepage under [**List of ASP stories that have translations**](http://global-asp.github.io/stories/#list-of-asp-stories-that-have-translations). There are links to each translation as well as to the original story on the African Storybook website.

Here's a screenshot from that page for the story you were looking for:

![image](https://cloud.githubusercontent.com/assets/9295750/15022820/597319e8-11e2-11e6-833f-b2fd1ac57d0d.png)
