### ISSUE TITLE
Double metadata in Translator

### ISSUE THREAD

**Issue by espensj** [global-asp/global-asp#13]
The metadata appears twice in Translator. It can also be a bit spacious, so I suggest making it all on one line. That way the "review" button comes higher up and is more prominent. 

**Suggestion revision**
![revised](https://cloud.githubusercontent.com/assets/12679303/14272314/ded22360-fab6-11e5-812f-833563acda78.png)

**Current**
![screen shot 2016-04-04 at 10 45 57 pm](https://cloud.githubusercontent.com/assets/12679303/14272335/0c32537a-fab7-11e5-801c-4cfb9e22ec1e.png)

**Comment by dohliam** [comment]
This issue has been moved to the [gasp-translator](https://github.com/dohliam/gasp-translator/issues/17 repository). To keep things organized, let's try to report bugs that have to do with the Translator app in the gasp-translator repo, and keep the global-asp main repository for bugs that have to do with the translated story text we are storing here.
