### ISSUE TITLE
Bug in translator image viewer

### ISSUE THREAD

**Issue by espensj** [global-asp/global-asp#16]
There is a bug in the translator image viewer for a couple of the stories – _Nozibele and the three hairs_ and _The honeyguide's revenge_ (here might be other stories with this problem). On pages that have more than one line, only the first line appears. it seems the problem is the use of quotation mark, which somehow breaks the text and hides it. 

![screen shot 2016-10-08 at 08 01 02](https://cloud.githubusercontent.com/assets/12679303/19214738/6d617b74-8d3f-11e6-9f5e-373e169d9848.png)

![screen shot 2016-10-08 at 10 24 49](https://cloud.githubusercontent.com/assets/12679303/19214814/912e0d36-8d41-11e6-8fe0-8265b4e7074f.png)

**Comment by dohliam** [comment]
Moved to the [gasp-translator repo](https://github.com/dohliam/gasp-translator/issues/23)
