### ISSUE TITLE
Corrections in Norwegian translator

### ISSUE THREAD

**Issue by espensj** [global-asp/global-asp#3]
https://global-asp.github.io/experiments/gt-no/?0007
Current: "Nå oversetter fortelling"
Change to: "Nå oversettes fortelling"

Current: "Global-ASP Translator Norsk"
Change to: "Global-ASP oversetter på norsk"

Current: "opprinnelige ASP historie"
Change to: "opprinnelig ASP historie"

Current: ""Hvis du er fornøyd med din oversettelse"
Change to: ""Hvis du er fornøyd med oversettelsen din" [both are correct, but this more standard]

Also, note the doubling of licence info:
![image](https://cloud.githubusercontent.com/assets/12679303/10556773/cf294222-7442-11e5-863c-c78493e1fbab.png)

**Comment by dohliam** [comment]
> Current: "Nå oversetter fortelling"
> Change to: "Nå oversettes fortelling"

Fixed.

> Current: "opprinnelige ASP historie"
> Change to: "opprinnelig ASP historie"

Fixed.

> Current: ""Hvis du er fornøyd med din oversettelse"
> Change to: ""Hvis du er fornøyd med oversettelsen din" [both are correct, but this more standard]

Fixed.

**(Reload page to see changes.)**

**Comment by dohliam** [comment]
> Current: "Global-ASP Translator Norsk"
> Change to: "Global-ASP oversetter på norsk"

I haven't changed this (yet) because the name of the application is "Global-ASP Translator", in other words this is a proper name. Given this context, does it make sense to translate the name too? Not sure myself, so I'll go with your suggestion. :smile:

**Comment by dohliam** [comment]
PS, further issues with the Global-ASP Translator should be filed in the [gasp-translator repository](https://github.com/dohliam/gasp-translator/issues) rather than here. :sweat_smile:
