### ISSUE TITLE
Suggestion for new GUI

### ISSUE THREAD

**Issue by espensj** [global-asp/global-asp#4]
This is my suggestion for a new GUI:

You start here:
![1 start](https://cloud.githubusercontent.com/assets/12679303/10557074/e5039440-7450-11e5-9fdb-a3c742bfee4e.png)

You type your language. For 99% of languages we are likely to ever encounter it's simply a matter of matching English and the name of the language in the language itself, such as "Danish" and "dansk". If either of these two words are entered as the name of the language, you get to this page:

![2 language](https://cloud.githubusercontent.com/assets/12679303/10557108/355fbe90-7452-11e5-8170-59c2dbb48705.png)

If the language is not recognized (there are no stories translated yet) you get the same page, except the link. If you click on the link "Click here for a full list", you get this:

![3 list of stories](https://cloud.githubusercontent.com/assets/12679303/10557113/589dd7f2-7452-11e5-921e-825956b6b71f.png)

Note that I've added sorting function and "recommended" (not the best word choice, perhaps). The idea is that some stories are quality assured – by ASP, or the Global ASP team, since there are quite few non-edited stories out there.

**Comment by dohliam** [comment]
This is [an existing issue](https://github.com/dohliam/gasp-translator/issues/4) in the gasp-translator repository. I've moved your comment there, so I will close this issue now.
