### ISSUE TITLE
Purge cached data in translator

### ISSUE THREAD

**Issue by espensj** [global-asp/global-asp#7]
I would like a button to purge cached text in the translator. Now, if I want to translate a story to two or more languages, I have to delete the text for each text box manually.

I translated this into Spanish, but if I want to translate it into Farsi next, I have to delete box by box:
![screen shot 2015-11-14 at 1 32 31 pm](https://cloud.githubusercontent.com/assets/12679303/11165939/86b59790-8ad4-11e5-9e25-c7510f625d33.png)

**Comment by dohliam** [comment]
Great idea! This should be very simple to add.

**Comment by dohliam** [comment]
Actually, this should be with the translator app -- closing this now and moving it there.

**Comment by dohliam** [comment]
@espensj: You can track progress on this issue here:

https://github.com/dohliam/gasp-translator/issues/14
