### ISSUE TITLE
ISO code for Norwegian

### ISSUE THREAD

**Issue by dohliam** [global-asp/global-asp#8]
@espensj Now that we have both bokmål and nynorsk, we should probably standardize on using "nb" as the language code for bokmål instead of "no". Do you agree?

**Comment by espensj** [comment]
Yes. Might someone search for "norsk" and not find anything? What about the translator? If you type "norsk", will it not recognize it, or should it treat it as bokmål? Or prompt, "Do you mean bokmål or nynorsk?

**Comment by dohliam** [comment]
If you're talking about the GASP Translator, it will recognize any combination of `no`, `nn`, `norsk`, `Norwegian`, `bokmål`, `nynorsk` etc etc.

The stories are listed on the main website under their actual language name (in native form as well as English translation) rather than their ISO code, so this shouldn't make a difference for people searching. The ISO code here is just an internal representation that links to all of the possible translated forms of the language name.
